server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/api_relatorio_vendas
    username: postgres                             
    password: adm123                               
  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      jdbc:
        lob:
          non-contextual-creation: true
  output:
    ansi:
      enabled: always
